//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee
    {
        public int Id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> member_fee { get; set; }
        public Nullable<int> expected_fee { get; set; }
        public Nullable<int> user_id { get; set; }
        public byte[] user_name { get; set; }
        public Nullable<System.DateTime> datesubmitted { get; set; }
    }
}
